services:
  app:
    image: ghcr.io/evilprophet/cryptosik:latest
    container_name: cryptosik
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./data:/var/www/html/data
    restart: unless-stopped

  scheduler:
    image: ghcr.io/evilprophet/cryptosik:latest
    container_name: cryptosik-scheduler
    env_file:
      - .env
    volumes:
      - ./data:/var/www/html/data
    working_dir: /var/www/html
    user: www-data
    command: php artisan schedule:work --no-interaction
    depends_on:
      - app
    restart: unless-stopped
